### ISSUE TITLE
check! exact number of hits

### ISSUE THREAD

**Issue by nagisa** [matklad/cov-mark#3]
I want to suggest an addition to the API of this crate – checking the number of times coverage mark was hit.

This is in particular useful for testing things like "this must have been dropped exactly this many times" (i.e. where you want to assure that no double drops are occurring).

**Comment by nagisa** [comment]
Would such a change be acceptable for this repository?

**Comment by matklad** [comment]
I guess I'd like to see what the API and use cases would look like :)

One wrinkle here is that, if tests are running in multiple threads, you can't be sure about the exact count -- mark are static, so, if some other thread hits the mark, you get a phantom +1.

This can give only "false positive" (test passes while it shouldn't) for binary "was the mark hit" question, but for "was hit exactly N times" this can also give just a wrong answer. 

This might be fixed with some clever use of thread-locals, I suppose, but I fear that that would complicate implementation somewhat. 

So, I'd say this:

* if there's simple enough implementation with unsurprising semantics, than, sure, it makes sense to add this to this crate.
* if there are some non-trivial tradeoffs, I would be more comfortable with a fork -- the crate is deliberately small to allow easy tweaking for the use-case (rust-analyzer, for example, vendors it without any really good reason).
